server:
  port: 8072
spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http:/localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

#DELETED IN TUTORIAL AS ITS CONNECTED THROUGH CONFIG SERVER
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "gatewayserver"
    description: "Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        accounts: DEBUG