spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Bank accounts related Production APIs "
  contactDetails:
    name: "Tom H - QA Lead"
    email: "prakash.anandakumar@acentura.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345